export const data = [
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 5,
    Confiança: 5,
    "Aprendizado contínuo": 5,
    Autonomia: 5,
    "Integridade e Coerência": 3,
    "Qualidade de vida": 3,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 3,
    Confiança: 4,
    "Aprendizado contínuo": 3,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 5,
    Confiança: 5,
    "Aprendizado contínuo": 3,
    Autonomia: 3,
    "Integridade e Coerência": 5,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 5,
    Confiança: 5,
    "Aprendizado contínuo": 4,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 3,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 4,
    Confiança: 4,
    "Aprendizado contínuo": 4,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 3,
  },
  {
    "Você possui papel de liderança na Going2?": "CEO",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 5,
    Confiança: 4,
    "Aprendizado contínuo": 3,
    Autonomia: 3,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 3,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 4,
    Confiança: 5,
    "Aprendizado contínuo": 4,
    Autonomia: 3,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 2,
    "Segurança Psicológica": 3,
    Confiança: 2,
    "Aprendizado contínuo": 5,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 4,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 5,
    Confiança: 5,
    "Aprendizado contínuo": 4,
    Autonomia: 4,
    "Integridade e Coerência": 5,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 4,
    Confiança: 5,
    "Aprendizado contínuo": 4,
    Autonomia: 4,
    "Integridade e Coerência": 5,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 4,
    Confiança: 5,
    "Aprendizado contínuo": 5,
    Autonomia: 5,
    "Integridade e Coerência": 5,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 4,
    Confiança: 4,
    "Aprendizado contínuo": 3,
    Autonomia: 3,
    "Integridade e Coerência": 3,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 5,
    Confiança: 5,
    "Aprendizado contínuo": 3,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 2,
    "Segurança Psicológica": 3,
    Confiança: 2,
    "Aprendizado contínuo": 3,
    Autonomia: 2,
    "Integridade e Coerência": 2,
    "Qualidade de vida": 1,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 5,
    Confiança: 4,
    "Aprendizado contínuo": 3,
    Autonomia: 3,
    "Integridade e Coerência": 3,
    "Qualidade de vida": 4,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 3,
    Confiança: 4,
    "Aprendizado contínuo": 5,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 3,
    "Segurança Psicológica": 4,
    Confiança: 4,
    "Aprendizado contínuo": 4,
    Autonomia: 5,
    "Integridade e Coerência": 3,
    "Qualidade de vida": 2,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 5,
    Confiança: 4,
    "Aprendizado contínuo": 3,
    Autonomia: 5,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 5,
    Confiança: 5,
    "Aprendizado contínuo": 5,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 4,
    Confiança: 5,
    "Aprendizado contínuo": 4,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 3,
    Confiança: 5,
    "Aprendizado contínuo": 5,
    Autonomia: 5,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 4,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 3,
    Confiança: 4,
    "Aprendizado contínuo": 3,
    Autonomia: 4,
    "Integridade e Coerência": 2,
    "Qualidade de vida": 4,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 3,
    Confiança: 4,
    "Aprendizado contínuo": 3,
    Autonomia: 5,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 2,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 4,
    Confiança: 4,
    "Aprendizado contínuo": 2,
    Autonomia: 5,
    "Integridade e Coerência": 3,
    "Qualidade de vida": 1,
  },
  {
    "Você possui papel de liderança na Going2?": "Não",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 5,
    Confiança: 4,
    "Aprendizado contínuo": 3,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 4,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 4,
    Confiança: 4,
    "Aprendizado contínuo": 3,
    Autonomia: 4,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 4,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 5,
    "Segurança Psicológica": 3,
    Confiança: 4,
    "Aprendizado contínuo": 4,
    Autonomia: 3,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 2,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 3,
    "Segurança Psicológica": 4,
    Confiança: 4,
    "Aprendizado contínuo": 4,
    Autonomia: 3,
    "Integridade e Coerência": 3,
    "Qualidade de vida": 5,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 4,
    Confiança: 5,
    "Aprendizado contínuo": 3,
    Autonomia: 4,
    "Integridade e Coerência": 3,
    "Qualidade de vida": 3,
  },
  {
    "Você possui papel de liderança na Going2?":
      "Liderança (Head, Coordenador, Techlead, PO)",
    "Liberdade de Expressão": 4,
    "Segurança Psicológica": 2,
    Confiança: 3,
    "Aprendizado contínuo": 3,
    Autonomia: 2,
    "Integridade e Coerência": 4,
    "Qualidade de vida": 1,
  },
];
